# Generated by Django 5.2.8 on 2025-11-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('contacto', models.CharField(help_text='Teléfono o email', max_length=200)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('cocinas_integrales', 'Cocinas Integrales'), ('closets', 'Closets y Armarios'), ('puertas', 'Puertas'), ('muebles_personalizados', 'Muebles Personalizados'), ('instalacion_montaje', 'Instalación y Montaje')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('materiales', models.TextField(help_text='Ejemplo: Madera de pino, herrajes de acero inoxidable')),
                ('imagen', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
