# Generated by Django 5.2.8 on 2025-11-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpinteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destinatario', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Referencia adicional (apto, piso, etc.)', max_length=500)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('mercado_pago', 'Mercado Pago')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50)),
                ('productos_json', models.TextField(help_text='Productos en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
