# Generated by Django 5.2.8 on 2026-03-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpinteria', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_mueble', models.CharField(choices=[('cocinas_integrales', 'Cocinas Integrales'), ('closets', 'Closets y Armarios'), ('puertas', 'Puertas'), ('muebles_personalizados', 'Muebles Personalizados'), ('instalacion_montaje', 'Instalación y Montaje'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(help_text='Describe el mueble que necesitas, medidas, materiales preferidos, etc.')),
                ('imagen_referencia', models.ImageField(blank=True, help_text='Sube una imagen de referencia (opcional)', null=True, upload_to='cotizaciones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
