# Generated by Django 5.2.8 on 2026-04-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpinteria', '0005_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
