# Generated by Django 6.0.4 on 2026-04-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpinteria', '0006_producto_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('mercado_pago', 'Mercado Pago'), ('ticket_tienda', 'Pago en Carpintería (Ticket)')], max_length=50),
        ),
    ]
